# Section 5 inventory helper used by the notebook audit.
from __future__ import annotations
from collections import defaultdict
from typing import Any
import scripts.section_4 as s4
from .references import NATURE_ORDER, NOTEBOOK_REFS, SCRIPT_REFS

from .inventory_inventory_item import inventory_item

def get_hyperparameter_inventory() -> list[dict[str, str]]:
    return [
        inventory_item(name="input_shape", code_example="Input(shape=(32,32,3))", category="architecture", nature_precise="structurel impose par la tache", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="32 x 32 x 3", retained_value="32 x 32 x 3", influence="fixe la forme des donnees d'entree et contraint la premiere couche du reseau"),
        inventory_item(name="output_units", code_example="Dense(10, activation='softmax')", category="architecture", nature_precise="structurel impose par la tache", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="10", retained_value="10", influence="impose la dimension de sortie du classifieur et doit coincider avec le nombre de classes"),
        inventory_item(name="num_conv_layers", code_example="model.add(Conv2D(...))", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="1 couche convolutionnelle", retained_value="1 couche convolutionnelle", influence="controle la profondeur de l'extraction locale et la croissance du champ recepteur effectif"),
        inventory_item(name="filters", code_example="Conv2D(filters=8, ...)", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="8", retained_value="8", influence="modifie la largeur de la representation convolutionnelle et le nombre de poids appris"),
        inventory_item(name="kernel_size", code_example="Conv2D(..., kernel_size=(3,3), ...)", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="(3, 3)", retained_value="(3, 3)", influence="controle le voisinage local explore et participe directement au champ recepteur"),
        inventory_item(name="padding", code_example="Conv2D(..., padding='same')", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="same", retained_value="same", influence="preserve la resolution spatiale de sortie et conditionne la taille des tenseurs transmis aux couches suivantes"),
        inventory_item(name="pool_size", code_example="MaxPool2D(pool_size=(2,2))", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="(2, 2)", retained_value="(2, 2)", influence="reduit la resolution spatiale, diminue le cout calculatoire et agrandit le champ recepteur effectif des couches profondes"),
        inventory_item(name="conv_to_dense_bridge", code_example="Flatten()", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="Flatten", retained_value="Flatten", influence="fixe la transition convolution-dense et donc la taille d'entree de la tete de classification"),
        inventory_item(name="dense_units", code_example="Dense(64, activation='relu')", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="64", retained_value="64", influence="controle la largeur de la tete de classification et la capacite expressive de la partie dense"),
        inventory_item(name="activation_hidden", code_example="activation='relu'", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="ReLU", retained_value="ReLU", influence="introduit la non-linearite et limite en pratique l'attenuation du gradient dans les premieres couches"),
        inventory_item(name="activation_output", code_example="activation='softmax'", category="architecture", nature_precise="ajustable de conception", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="softmax", retained_value="softmax", influence="rend la sortie interpretable comme distribution de probabilites sur les classes"),
        inventory_item(name="loss", code_example="compile(loss='categorical_crossentropy', ...)", category="optimisation", nature_precise="entrainement", location=f"{NOTEBOOK_REFS['compile']} ; {SCRIPT_REFS['train']}", initial_value="categorical_crossentropy", retained_value="categorical_crossentropy", influence="definit la quantite dont le gradient pilote l'apprentissage ; ici elle est adaptee a une sortie softmax et a des labels one-hot"),
        inventory_item(name="optimizer", code_example="SGD(...), Adam(...)", category="optimisation", nature_precise="entrainement", location=f"{NOTEBOOK_REFS['compile']} ; {SCRIPT_REFS['optimizer']}", initial_value="SGD", explored_values="SGD, SGD+Momentum, Adam", retained_value="comparaison explicite en Section 4", influence="modifie la dynamique de convergence, le lissage des gradients et la sensibilite au pas d'apprentissage"),
        inventory_item(name="learning_rate", code_example="SGD(learning_rate=0.01), Adam(learning_rate=0.001)", category="optimisation", nature_precise="entrainement", location=f"{NOTEBOOK_REFS['compile']} ; {SCRIPT_REFS['optimizer']}", initial_value="0.01", explored_values="0.01 pour SGD et SGD+Momentum ; 0.001 pour Adam", retained_value="0.01 (SGD), 0.001 (Adam)", influence="multiplie directement le gradient dans les mises a jour ; trop grand il destabilise la descente, trop faible il ralentit fortement la convergence"),
        inventory_item(name="momentum", code_example="SGD(..., momentum=0.0) / SGD(..., momentum=0.9)", category="optimisation", nature_precise="entrainement", location=f"{NOTEBOOK_REFS['compile']} ; {SCRIPT_REFS['optimizer']}", initial_value="0.0", explored_values="0.0 et 0.9", retained_value="0.9 pour la comparaison SGD+Momentum", influence="ajoute une inertie directionnelle qui lisse les fluctuations du gradient entre deux mini-batches"),
        inventory_item(name="beta_1", code_example="Adam(..., beta_1=0.9, ...)", category="optimisation", nature_precise="entrainement", location=SCRIPT_REFS['optimizer'], explored_values="0.9", retained_value="0.9", influence="controle le lissage du premier moment dans Adam"),
        inventory_item(name="beta_2", code_example="Adam(..., beta_2=0.999, ...)", category="optimisation", nature_precise="entrainement", location=SCRIPT_REFS['optimizer'], explored_values="0.999", retained_value="0.999", influence="controle le lissage du second moment dans Adam"),
        inventory_item(name="adam_eta", code_example="Adam(..., epsilon=1e-7)", category="optimisation", nature_precise="entrainement", location=SCRIPT_REFS['optimizer'], explored_values="1e-7", retained_value="1e-7", influence="stabilise numeriquement le denominateur de l'update d'Adam ; elle correspond au terme note eta dans le rapport"),
        inventory_item(name="batch_size", code_example="fit(..., batch_size=...)", category="protocole", nature_precise="entrainement", location=f"{NOTEBOOK_REFS['fit_main']} ; {NOTEBOOK_REFS['fit_reload']} ; {SCRIPT_REFS['section4']}", initial_value="32", explored_values="8 ; {8,16,32,64,128}", retained_value="32 pour la baseline et l'etude optimiseurs ; grille {8,16,32,64,128} pour l'etude batch-size", influence="agit sur le bruit du gradient, le nombre d'updates par epoch et le compromis entre stabilite et cout calculatoire"),
        inventory_item(name="epochs", code_example="fit(..., epochs=...)", category="protocole", nature_precise="entrainement", location=f"{NOTEBOOK_REFS['fit_main']} ; {NOTEBOOK_REFS['fit_reload']} ; {SCRIPT_REFS['section4']}", initial_value="20", explored_values="10 ; 8", retained_value="8 pour les comparaisons controlees de la Section 4", influence="fixe le budget d'apprentissage en passages sur la base et conditionne le niveau de convergence atteint"),
        inventory_item(name="shuffle", code_example="fit(..., shuffle=True)", category="protocole", nature_precise="entrainement", location=SCRIPT_REFS['train'], initial_value="defaut Keras sur le notebook", explored_values="True dans la pipeline reproductible", retained_value="True", influence="limite les effets d'ordre entre epochs et stabilise l'estimation du gradient stochastique"),
        inventory_item(name="dropout_rate", code_example="Dropout(0.0)", category="regularisation", nature_precise="regularisation", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="0.0", retained_value="0.0", influence="si le taux etait strictement positif, il reduirait la co-adaptation des neurones et le risque de sur-apprentissage ; ici son effet empirique est nul"),
        inventory_item(name="l2_lambda", code_example="kernel_regularizer=l2(0.00)", category="regularisation", nature_precise="regularisation", location=f"{NOTEBOOK_REFS['model']} ; {SCRIPT_REFS['model']}", initial_value="0.00", retained_value="0.00", influence="si le coefficient etait positif, il penaliserait les poids trop grands et lisserait le modele ; ici son effet empirique est nul"),
    ]
